
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
  
- name: Install common utilities and fail2ban
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - fail2ban
    state: present

- name: Start and enable fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
